                                    <option selected value='permII'>Пермь II</option>
									<option  value='permI'>Пермь I</option>
									<option  value='kungur'>Кунгур</option>
									<option  value='chusovskaya'>Чусовская</option>
									<option  value='vereshchagino'>Верещагино</option>
									<option  value='perm-sortirovochnaya'>Пермь-Сортировочная</option>
									<option  value='komsomolskaya'>Комсомольская</option>
									<option  value='jeleznodorojnyy'>о.п. Железнодорожная</option>
									<option  value='promuchastok'>Промучасток</option>
									<option  value='kurya'>Курья</option>
									<option  value='lasva'>Ласьва</option>
									<option  value='mysy'>Мысы</option>
									<option  value='overyata'>Оверята</option>
									<option  value='strelka'>Стрелка</option>
									<option  value='uval'>Увал</option>
									<option  value='shabunichi'>Шабуничи</option>
									<option  value='1394km'>Нижнее Брагино (1394 км)</option>
									<option  value='udaly'>Удалы</option>
									<option  value='chaykovskaya'>Чайковская</option>
									<option  value='vojakovo'>Вожаково</option>
									<option  value='yushkovo'>Юшково</option>
									<option  value='syuzva'>Сюзьва</option>
									<option  value='1375km'>Бураки (1375 км)</option>
									<option  value='grigorevskaya'>Григорьевская</option>
									<option  value='1366km'>Новокошкино (1366 км)</option>
									<option  value='mokino'>Мокино</option>
									<option  value='1358km'>Большая Ния (1358 км)</option>
									<option  value='obva'>Обва</option>
									<option  value='mendeleevo'>Менделеево</option>
									<option  value='puzyata'>Пузята</option>
									<option  value='kuketskiy'>Кукетский</option>
									<option  value='anikino'>Аникино</option>
									<option  value='zyukay'>Зюкай</option>
									<option  value='1312km'>Рябины (1312 км)</option>
									<option  value='subbotniki'>Субботники</option>
									<option  value='hrustali'>Хрустали</option>
									<option  value='putino'>Путино</option>
									<option  value='borodulino'>Бородулино</option>
									<option  value='volegovo'>Волегово</option>
									<option  value='babiki'>Бабики</option>
									<option  value='shnyry'>Шныры</option>
									<option  value='kuzma'>Кузьма</option>
									<option  value='filincy'>Филинцы</option>
									<option  value='kabalud'>Кабалуд</option>
									<option  value='lyp'>Лып</option>
									<option  value='kez'>Кез</option>
									<option  value='klyuchevskoe'>Ключевское</option>
									<option  value='segedur'>Сегедур</option>
									<option  value='pushmezi'>Пушмези</option>
									<option  value='chepca'>Чепца</option>
									<option  value='post1217km'>Пост 1217 км</option>
									<option  value='pibanshur'>Пибаньшур</option>
									<option  value='shur'>Шур</option>
									<option  value='balezino'>Балезино</option>
									<option  value='dzerjinskaya'>Дзержинская</option>
									<option  value='slavyanova'>Славянова</option>
									<option  value='motoviliha'>Мотовилиха</option>
									<option  value='yazovaya'>Язовая</option>
									<option  value='yubileynaya'>Юбилейная</option>
									<option  value='balmoshnaya'>Балмошная</option>
									<option  value='kislotnyy'>Кислотный</option>
									<option  value='molodejnaya'>Молодежная</option>
									<option  value='kamges'>КамГЭС</option>
									<option  value='levshino'>Левшино</option>
									<option  value='bannayagora'>Банная Гора</option>
									<option  value='5km'>Поселок Пятый километр (5 км)</option>
									<option  value='palniki'>Пальники</option>
									<option  value='9km'>Горки (9 км)</option>
									<option  value='12km'>Красная Слудка (12 км)</option>
									<option  value='13km'>Ельники (13 км)</option>
									<option  value='bobki'>Бобки</option>
									<option  value='22km'>Дачная (22 км)</option>
									<option  value='25kmugleuralskaya'>25 км (Углеуральская)</option>
									<option  value='divya'>Дивья</option>
									<option  value='29km'>Путейская (29 км)</option>
									<option  value='32km'>Пасечный Хутор (32 км)</option>
									<option  value='polazna'>Полазна</option>
									<option  value='42km'>Родники (42 км)</option>
									<option  value='yarino'>Ярино</option>
									<option  value='56km'>56 км</option>
									<option  value='kuhtym'>Кухтым</option>
									<option  value='66km'>66 км</option>
									<option  value='kyj'>Кыж</option>
									<option  value='77km'>Мальцево (77 км)</option>
									<option  value='bokovaya'>Боковая</option>
									<option  value='83km'>Полетаенки (83 км)</option>
									<option  value='borodkino'>Бородкино</option>
									<option  value='tabory'>Таборы</option>
									<option  value='98km'>Баташата (98 км)</option>
									<option  value='tihaya'>Тихая</option>
									<option  value='104km'>Канюки (104 км)</option>
									<option  value='106km'>Косьвинский (106 км)</option>
									<option  value='parma'>Парма</option>
									<option  value='shestaki'>Шестаки</option>
									<option  value='ugleuralskaya'>Углеуральская</option>
									<option  value='150km'>150 км</option>
									<option  value='nyar'>Няр</option>
									<option  value='obogatitel'>Обогатитель</option>
									<option  value='kizel'>Кизел</option>
									<option  value='116km'>Технический (116 км)</option>
									<option  value='rasik'>Расик</option>
									<option  value='kopi'>Копи</option>
									<option  value='148km'>Карьер Известняк (148 км)</option>
									<option  value='vsevolodo-vilva'>Всеволодо-Вильва</option>
									<option  value='yayva'>Яйва</option>
									<option  value='174km'>Замельничный (174 км)</option>
									<option  value='lyuzen'>Люзень</option>
									<option  value='183km'>Уньва (183 км)</option>
									<option  value='berezniki-sortirovochnaya'>Березники-Сортировочная</option>
									<option  value='parkkaliynaya'>Парк Калийная</option>
									<option  value='201km'>201 км</option>
									<option  value='202km'>202 км</option>
									<option  value='polovinka-chusovskaya'>Половинка-Чусовская</option>
									<option  value='verhnyayagubaha'>Верхняя Губаха</option>
									<option  value='gubaha'>Губаха</option>
									<option  value='gubaha-passajirskaya'>Губаха-Пассажирская</option>
									<option  value='nagornaya'>Нагорная</option>
									<option  value='usva'>Усьва</option>
									<option  value='mahovatnya'>Маховатня</option>
									<option  value='basseg'>Бассег</option>
									<option  value='baskaya'>Баская</option>
									<option  value='zagotovka'>Заготовка</option>
									<option  value='gruzdi'>Грузди</option>
									<option  value='utes'>Утес</option>
									<option  value='antabary'>Антабары</option>
									<option  value='6kmchusovskaya'>6 км (Чусовская)</option>
									<option  value='3km'>Переезд 3 км (3 км)</option>
									<option  value='golovanovo'>Голованово</option>
									<option  value='25kmchusovskaya'>Пасека (25 км)</option>
									<option  value='adishchevo'>Адищево</option>
									<option  value='30km'>Казарма (30 км)</option>
									<option  value='38km'>Новые Ляды (38 км)</option>
									<option  value='lyady'>Ляды</option>
									<option  value='zalesnaya'>Залесная</option>
									<option  value='48km'>48 км</option>
									<option  value='sylva'>Сылва</option>
									<option  value='kulikovka'>Куликовка</option>
									<option  value='54km'>Геологи (54 км)</option>
									<option  value='alebastrovo'>Алебастрово</option>
									<option  value='valejnaya'>Валежная</option>
									<option  value='73km'>Каменка (73 км)</option>
									<option  value='komarihinskaya'>Комарихинская</option>
									<option  value='kutamysh'>Кутамыш</option>
									<option  value='selyanka'>Селянка</option>
									<option  value='101km'>101 км</option>
									<option  value='vereinskiy'>Вереинский</option>
									<option  value='kalino'>Калино</option>
									<option  value='120km'>120 км</option>
									<option  value='lyamino'>Лямино</option>
									<option  value='shibanovo'>Шибаново</option>
									<option  value='129km'>129 км</option>
									<option  value='130km'>130 км</option>
									<option  value='136km'>Земля Постникова (136 км)</option>
									<option  value='139km'>Ермак (139 км)</option>
									<option  value='arhipovka'>Архиповка</option>
									<option  value='skalnyy'>Скальный</option>
									<option  value='vsesvyatskaya'>Всесвятская</option>
									<option  value='bagul'>Багул</option>
									<option  value='pashiya'>Пашия</option>
									<option  value='koyva'>Койва</option>
									<option  value='vijay'>Вижай</option>
									<option  value='laki'>Лаки</option>
									<option  value='biser'>Бисер</option>
									<option  value='teplayagora'>Теплая Гора</option>
									<option  value='ust-tiskos'>Усть-Тискос</option>
									<option  value='evropeyskaya'>Европейская</option>
									<option  value='6kmkalino'>6 км (Калино)</option>
									<option  value='lyazgino'>Лязгино</option>
									<option  value='lysva'>Лысьва</option>
									<option  value='24km'>Заболотная (24 км)</option>
									<option  value='28km'>Сокол (28 км)</option>
									<option  value='nevidimka'>Невидимка</option>
									<option  value='kormovishche'>Кормовище</option>
									<option  value='kumysh'>Кумыш</option>
									<option  value='kyn'>Кын</option>
									<option  value='rassolenko'>Рассоленко</option>
									<option  value='124km'>124 км</option>
									<option  value='un'>Унь</option>
									<option  value='harenki'>Харенки</option>
									<option  value='ilim'>Илим</option>
									<option  value='178km'>Пермяки (178 км)</option>
									<option  value='vyrubki'>Вырубки</option>
									<option  value='utkinskiyzavod'>Уткинский завод</option>
									<option  value='204km'>204 км</option>
									<option  value='plyusniha'>Плюсниха</option>
									<option  value='kuzino'>Кузино</option>
									<option  value='1436km'>1436 км</option>
									<option  value='baharevka'>Бахаревка</option>
									<option  value='1447km'>Липовая Гора (1447 км)</option>
									<option  value='nyashino'>Няшино</option>
									<option  value='ferma'>Ферма</option>
									<option  value='kochkino'>Кочкино</option>
									<option  value='klestovskiy'>Клестовский</option>
									<option  value='gorbunovo'>Горбуново</option>
									<option  value='mulyanka'>Мулянка</option>
									<option  value='1470km'>Медовый Дол (1470 км)</option>
									<option  value='yug'>Юг</option>
									<option  value='1478km'>1478 км</option>
									<option  value='yanychi'>Янычи</option>
									<option  value='kukushtan'>Кукуштан</option>
									<option  value='1492km'>СНТ Вита (1492 км)</option>
									<option  value='kurashimskiy'>Курашимский</option>
									<option  value='1505km'>Кыласово (1505 км)</option>
									<option  value='chikali'>Чикали</option>
									<option  value='kamai'>Камаи</option>
									<option  value='kishert'>Кишерть</option>
									<option  value='1559km'>Саламатово (1559 км)</option>
									<option  value='pyatkovo'>Пятково</option>
									<option  value='shkolnaya'>Школьная</option>
									<option  value='shumkovo'>Шумково</option>
									<option  value='1572km'>Верхняя Опалиха (1572 км)</option>
									<option  value='tyurikovo'>Тюриково</option>
									<option  value='tulumbasy'>Тулумбасы</option>
									<option  value='lek'>Лек</option>
									<option  value='kordon'>Кордон</option>
									<option  value='gluhar'>Глухарь</option>
									<option  value='shutem'>Шутем</option>
									<option  value='1624km'>Нижняя Баская (1624 км)</option>
									<option  value='shamary'>Шамары</option>
									<option  value='kozyal'>Козьял</option>
									<option  value='vogulka'>Вогулка</option>
									<option  value='biz'>Бизь</option>
									<option  value='shalya'>Шаля</option>
									<option  value='1406km'>1406 км</option>
									<option  value='platoshino'>Платошино</option>
									<option  value='ergach'>Ергач</option>
									<option  value='bliny'>Блины</option>
									<option  value='gipsy'>Гипсы</option>
									<option  value='irenskiy'>Иренский</option>
									<option  value='1533km'>Шпальник (1533 км)</option>
									<option  value='lesnayapolyanka'>Лесная Полянка</option>
									<option  value='berezniki-sortirovochnayaparkp'>Березники-Сортировочная парк "П"</option>
									<option  value='ekaterinburg'>Екатерибург-Пассажирский</option>
									<option  value='nikitino'>Никитино</option>
									<option  value='reyda'>Рейда</option>
									<option  value='krasnokamsk'>Краснокамск</option>
									<option  value='kabelnaya'>Кабельная</option>
									<option  value='ppi'>Комплекс ППИ</option>